kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-pv-claim
  labels:
    app: zk
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
